### PR TITLE
Bump CMake version to 3.12.3

### LINKED ISSUE #10: CMake version
Is there a specific reason for

> ... a modern version of CMake (3.7.2, instead of the Ubuntu 14.04 default of 2.8.12) ...

I mean, can we have the latest version or at least `3.9.0` for CMake? `3.9.0` is the version that has [introduced][1] the `find_dependency` macro that passes all the arguments to `find_package`, which simplifies a lot of dependency management in config files of cmake-generated libraries. I can work on a PR if simply bumping the package version introduces some trouble.

Thank you!

[1]: https://gitlab.kitware.com/cmake/cmake/blob/v3.9.0/Modules/CMakeFindDependencyMacro.cmake#L10

### PR DESCRIPTION
**Pull request by aytekinar**
Closes #10.

### CODE REVIEW

**Comment by aytekinar** [comment]
Seems to work on my Docker environment with `julia:1` as the base image. I hope the tests would pass. I have also changed `README.md` to point to `3.X.Y` instead of the fixed version number. I am not sure if I should keep the actual version number there...

**Comment by aytekinar** [comment]
Could we merge this one to `master`? Tagging would not be super necessary, but at least I can still use this repo's `master` instead of using my fork.

**Comment by stevengj** [comment]
I tagged v1.1.0

**Comment by aytekinar** [comment]
Thank you very much.

**Pull request merged**
